name: RandomCommand
version: '${project.version}'
main: com.ashkiano.randomcommand.RandomCommand
api-version: '1.16'
authors: [AshKiano]
description: Casts random commands from config to random players at random time.
website: https://www.ashkiano.com
commands:
  randomcommandreload:
    description: Reloads configuration of RandomCommand
    usage: /<command>
    permission: randomcommand.reload
