# List of commands to be randomly executed
commands:
  - 'say Hello, <player>!'
  - 'give <player> minecraft:diamond 1'
  - 'tp <player> 0 100 0'

# The minimum interval (in minutes) between command executions
minInterval: 1

# The maximum interval (in minutes) between command executions
maxInterval: 2

# If true, the interval between command executions will be fixed at the value of minInterval
fixedInterval: false

# If true, a message will be sent in the chat when a command is executed
chatNotification: true

# The message to be sent in the chat when a command is executed
# You can use '&1', '&2', etc. for text colors, and '<player>' for the player's name
chatMessage: '&6A command has been executed!'

# If true, a countdown will be displayed in the chat before a command is executed
countdownEnabled: true

# The interval (in minutes) at which the countdown messages will be displayed
countdownInterval: 5
