name: RandomCommand
version: '1.0'
main: com.ashkiano.randomcommand.RandomCommand
api-version: '1.20'
authors: [AshKiano]
description: Casts random commands from config to random players at random time.
website: https://www.ashkiano.com
